import type { Metadata } from 'next'
import './globals.css'
import Navbar from './Navbar/page'
import Footer from './Footer/page'


export const metadata: Metadata = {
  title: 'Azfar Suhail Portfolio',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex-col'>
      <Navbar />
      <body className={`min-h-screen bg-background font-sans antialiased mt-24 flex-grow `}>
  {children}
</body>

          <Footer/>
    </html>
  )
}