import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar/page'
import { Inter as FontSans } from "next/font/google"
import { cn } from "../lib/utils"
import Footer from './Footer/page'


export const metadata: Metadata = {
  title: 'Azfar Suhail Portfolio',
  description: 'Generated by create next app',
}

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex-col'>
      <Navbar />
      <body className={cn(
   "min-h-screen bg-background font-sans antialiased mt-24 flex-grow",
   fontSans.variable as string
)}
>
          {children}
          </body>
          <Footer/>
    </html>
  )
}
